version: "3.9"
services:
  mongo:
    image: "mongo:5.0"
    ports:
      - "25262:27017"
    volumes:
      - "data:/data/db"
  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "21290:8081"
volumes:
  data:
